micronaut:
  application:
    name: pixKeyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 5
  channels:
    keyManager:
      address: ${PIX_CLIENT_URL:`localhost:50051`}

##
# Jackson configuration
# https://github.com/micronaut-projects/micronaut-core/issues/240
# https://geowarin.com/correctly-handle-jsr-310-java-8-dates-with-jackson/
# https://www.baeldung.com/jackson-serialize-dates
##
jackson:
  serialization:
    writeDatesAsTimestamps: false